# Generated by Django 5.1.7 on 2025-04-04 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='UserData',
        ),
    ]
